default_install_hook_types: [pre-push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
        stages: [pre-push]
    -   id: check-json
        stages: [pre-push]
    -   id: check-toml
        stages: [pre-push]
    -   id: detect-private-key
        stages: [commit]
    -   id: detect-aws-credentials
        stages: [commit]
    -   id: double-quote-string-fixer
        stages: [pre-push]
    -   id: end-of-file-fixer
        stages: [pre-push]
    -   id: trailing-whitespace
        stages: [pre-push]
